fn main() {
    windows::build! {
        Windows::Win32::{
            Foundation::{
                CloseHandle,
                HANDLE,
                HINSTANCE,
                HWND,
                PSTR,
                WPARAM,
                LPARAM,
                LRESULT
            },
            System::{
                Console::AttachConsole,
                Com::{
                    IPersistFile,
                    CoInitializeEx,
                    CoCreateInstance,
                    CoTaskMemFree,
                    COINIT,
                    CLSCTX
                },
                DataExchange::{
                    AddClipboardFormatListener,
                    EnumClipboardFormats,
                    GetClipboardData,
                    GetClipboardFormatNameA,
                    GetClipboardOwner,
                    GetPriorityClipboardFormat,
                    OpenClipboard,
                    CloseClipboard
                },
                LibraryLoader::GetModuleHandleA,
                Threading::{
                    OpenProcess,
                    PROCESS_ACCESS_RIGHTS
                },
                ProcessStatus::K32GetProcessImageFileNameA,
                SystemServices::{CLIPBOARD_FORMATS, CHAR}
            },
            Graphics::Gdi::{BITMAPINFO, BITMAPINFOHEADER, BI_BITFIELDS},
            UI::Shell::{
                IKnownFolder,
                IKnownFolderManager,
                IShellLinkA,
                KnownFolderManager,
                ShellLink,
                ShellExecuteA,
                Shell_NotifyIconA,
                FOLDERID_Startup,
                NOTIFYICONDATAA,
                NOTIFY_ICON_DATA_FLAGS,
                NOTIFYICON_VERSION_4,
                NOTIFY_ICON_MESSAGE
            },
            UI::Controls::*,
            UI::WindowsAndMessaging::*
        }
    };
}
